title: "Pavan Kumar Gaggera Portfolio"
logo: /img/picture.jpg
description: "Machine Learning Engineer"
theme: jekyll-theme-minimal
email: pavankumargaggera05@gmail.com
linkedin: https://www.linkedin.com/in/pavan-gaggera/
url: "https://PavanKumarGaggera.github.io"
show_downloads: true
