title: "Pavan Kumar Gaggera Portfolio"
logo: /img/pic.jpg
description: "Machine Learning Engineer | AI/ML Solutions | AWS Certified"
theme: jekyll-theme-minimal
email: pavankumargaggera05@gmail.com
linkedin: https://www.linkedin.com/in/pavan-gaggera/
url: "https://PavanKumarGaggera.github.io"
show_excerpts: true
show_downloads: true
