title: "Pavan Kumar Gaggera Portfolio"
logo: /img/pic.jpg
description: "Machine Learning Engineer | AI/ML Solutions | AWS Certified"
theme: jekyll-theme-minimal
author: Pavan Kumar Gaggera
email: pavankumargaggera05@gmail.com
github_username: PavanKumarGaggera
linkedin: https://www.linkedin.com/in/pavan-gaggera/
baseurl: "" # Leave empty for GitHub Pages
url: "https://PavanKumarGaggera.github.io"
show_excerpts: true
show_downloads: true
